baseURL = "https://wacilpong.github.io/blog"
languageCode = "en-us"
title = "Roomy"
theme = "minimal"
# disqusShortname = "@disqus_SDumnkPwZd" delete this to disable disqus comments

[params]
    author = "Roomy Han"
    description = "Audio, Video, Disco"
    githubUsername = "wacilpong"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    favicon = "favicon.ico"
    css = ["css/custom.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.icon]]
    url = "https://github.com/wacilpong/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/areum-han-a10645118/"
    name = "linkedin"
    weight = 3
